### ISSUE TITLE
the position of the output has a problem on segmantation 

### ISSUE THREAD

**Issue by cancaglar** [HoloLabInc/HoloLabDnnPackages#2]
Greetings, first of all, thank you for these packages, they seem very successful and fast. I have not tested it on Android and iOS yet, I only tested it on Windows, but I think there is a small problem with segmentation. When I use the demo, the position of the output seems a little different.
![image](https://github.com/HoloLabInc/HoloLabDnnPackages/assets/59360242/9d145874-a194-43c1-8c3a-d59ce8a6272c)

**Comment by UnaNancyOwen** [comment]
Yes, It's a known issue. However, the cause is not yet known. If someone can help for debug this issue, We are welcome contributions. Thanks!
You can try SAM if you want, although it works a differently than semantic segmentation. It is available in the following repository.
https://github.com/UnaNancyOwen/MobileSAM-Unity
