### ISSUE TITLE
Integrate other Yolov9 models for Object Detection

### ISSUE THREAD

**Issue by kijz** [HoloLabInc/HoloLabDnnPackages#4]
Hey! I'm running into an issue when trying to include other yolov9 models.

I am actually just trying to integrate the same model that is included by default as a test, base yolov9-s from https://github.com/WongKinYiu/yolov9?tab=readme-ov-file

My end goal is actually to sometime integrate yolov9-tiny, to make it run faster on realtime applications.

I am running into an error when trying to run the inference:

```
Exception: [error] can not add post process to model for some reason. (IndexError: axis 3 is out of bounds shape of rank, 3
Assertion failure. Value was False
Expected: True)
HoloLab.DNN.ObjectDetection.ObjectDetectionModel_YOLOv9.AddPostProcess () (at ./Library/PackageCache/jp.co.hololab.dnn.objectdetection/Scripts/ObjectDetectionModel_YOLOv9.cs:163)
HoloLab.DNN.ObjectDetection.ObjectDetectionModel_YOLOv9.Initialize () (at ./Library/PackageCache/jp.co.hololab.dnn.objectdetection/Scripts/ObjectDetectionModel_YOLOv9.cs:122)
HoloLab.DNN.ObjectDetection.ObjectDetectionModel_YOLOv9..ctor (Unity.Sentis.ModelAsset model_asset, Unity.Sentis.BackendType backend_type) (at ./Library/PackageCache/jp.co.hololab.dnn.objectdetection/Scripts/ObjectDetectionModel_YOLOv9.cs:53)
```
but i made sure the input shape is `[1, 3, 640, 640]`.

I also tried directly downloading an onnx model from https://huggingface.co/Xenova/yolov9-onnx/blob/main/yolov9-c.onnx, 
which gave the following error: 
```
ArgumentException: RenderTextureDesc width must be greater than zero.
Parameter name: desc.width
UnityEngine.RenderTexture.ValidateRenderTextureDesc (UnityEngine.RenderTextureDescriptor& desc) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Graphics/Texture.cs:406)
UnityEngine.RenderTexture.GetTemporary (UnityEngine.RenderTextureDescriptor desc) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Graphics/Texture.cs:480)
```

This also did not work.

Do you know where this error might occur?

EDIT: 
i noticed your comment here: 
https://discussions.unity.com/t/implement-yolov9-mit-with-unity-sentis/367674/2
, but i failed to properly export the model weights to onnx. 
After running `lazy.py`, i don't get the converted model anywhere. 
can you help me out? :)

**Comment by UnaNancyOwen** [comment]
First, let me describe about repository of YOLOv9 MIT.
There are two repositories for YOLOv9.

1. https://github.com/WongKinYiu/yolov9 (not for you)
  This is an official implementation of YOLOv9 when the paper was released. It is licensed under the GPL. We refer to it as "YOLOv9" for distinction in here.

2. https://github.com/WongKinYiu/YOLO (for you)
  This is a volunteer implementation to reimplement YOLOv9 under the MIT license. It is licensed under the MIT license which is more permissive than the GPL. The repository name was changed from "YOLOv9 MIT" to "YOLO" due to historical circumstances. We refer to it as "YOLOv9 MIT" for distinction in here.

Next, the ObjectDetectionModel_YOLOv9 class of the HoloLab DNN Packages is support for the "YOLOv9 MIT". Probably, it will not work with the model of "YOLOv9". Please use the model of "YOLOv9 MIT".

Last, "YOLOv9 MIT" is a repository currently under development. Please report to the [issues](https://github.com/WongKinYiu/YOLO/issues) in "YOLOv9 MIT", about any problems with the export of ONNX format. I think they can help you. :)

If you have any problems with inference using ONNX of "YOLOv9 MIT", Please report to the issues in "HoloLab DNN Packages".
Thanks,

**Comment by UnaNancyOwen** [comment]
> https://discussions.unity.com/t/implement-yolov9-mit-with-unity-sentis/367674/2

By the way, I did a little checking "YOLOv9 MIT" just now.
It appears that the method of exporting to ONNX is different now.
If you want to use lazy.py as before, use a little older commit. 

```
git clone https://github.com/WongKinYiu/YOLO.git
git checkout e53ff097fdde2c9d613a7a763c52d6b74f58588e
```

This is a temporary workaround.
We need to eventually find a new way to do things. 
However, I will keep wait for development when officially release v1.0.

**Comment by kijz** [comment]
Thank you very much!
